# Generated by Django 6.0.1 on 2026-02-06 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'user'},
        ),
        migrations.AlterModelOptions(
            name='vehicle',
            options={'verbose_name': 'vehicle', 'verbose_name_plural': 'vehicle'},
        ),
    ]
