# Generated by Django 6.0.1 on 2026-02-06 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0002_alter_user_options_alter_vehicle_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('status', models.CharField(max_length=50)),
                ('seller_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Test.user')),
                ('vehicle_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Test.vehicle')),
            ],
            options={
                'verbose_name': 'listing',
                'verbose_name_plural': 'listing',
                'db_table': 'listing',
            },
        ),
        migrations.CreateModel(
            name='inspection_report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('ai_summary', models.TextField()),
                ('accidents_history', models.IntegerField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('listing_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Test.listing')),
            ],
            options={
                'verbose_name': 'inspection_report',
                'verbose_name_plural': 'inspection_report',
                'db_table': 'inspection_report',
            },
        ),
    ]
