# Generated by Django 6.0.1 on 2026-02-06 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0003_listing_inspection_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('status', models.CharField(max_length=50)),
                ('comment', models.TextField()),
                ('buyer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Test.user')),
                ('listing_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Test.listing')),
            ],
            options={
                'verbose_name': 'offer',
                'verbose_name_plural': 'offer',
                'db_table': 'offer',
            },
        ),
        migrations.CreateModel(
            name='testdrive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_date', models.DateField()),
                ('location', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('buyer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Test.user')),
                ('listing_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Test.listing')),
            ],
            options={
                'verbose_name': 'testdrive',
                'verbose_name_plural': 'testdrive',
                'db_table': 'testdrive',
            },
        ),
    ]
