# Generated by Django 6.0.1 on 2026-02-08 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0005_transaction'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='inspection_report',
            new_name='InspectionReport',
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name': 'transaction', 'verbose_name_plural': 'transaction'},
        ),
        migrations.RenameField(
            model_name='inspectionreport',
            old_name='listing_id',
            new_name='listing',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='seller_id',
            new_name='seller',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='vehicle_id',
            new_name='vehicle',
        ),
        migrations.RenameField(
            model_name='offer',
            old_name='buyer_id',
            new_name='buyer',
        ),
        migrations.RenameField(
            model_name='offer',
            old_name='listing_id',
            new_name='listing',
        ),
        migrations.RenameField(
            model_name='testdrive',
            old_name='buyer_id',
            new_name='buyer',
        ),
        migrations.RenameField(
            model_name='testdrive',
            old_name='listing_id',
            new_name='listing',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='buyer_id',
        ),
        migrations.AddField(
            model_name='transaction',
            name='buyer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='Test.user'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('seller', 'Seller'), ('buyer', 'Buyer'), ('admin', 'Admin')], default='buyer', max_length=50),
        ),
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('sold', 'Sold'), ('available', 'Available')], default='available', max_length=50),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterModelTable(
            name='transaction',
            table='transaction',
        ),
    ]
