# Generated by Django 6.0.1 on 2026-02-14 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_alter_serivce_rating_alter_serivce_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serivce',
            options={'verbose_name': 'Services', 'verbose_name_plural': 'Services'},
        ),
        migrations.AlterModelTable(
            name='serivce',
            table='services',
        ),
    ]
